
spring:
  jpa:
    # see: https://stackoverflow.com/questions/30549489/what-is-this-spring-jpa-open-in-view-true-property-in-spring-boot
    open-in-view: false
  thymeleaf:
    prefix: "classpath:/view-resources/"
    view-names: "*.th"
    suffix: ".html"
  mvc:
    servlet:
      load-on-startup: 1

server:
  servlet:
    context-path: "/easygo-web"
  ssl:
    enabled: true
    key-store: "classpath:easygoKs"
    key-store-type: "PKCS12"
    key-store-password: "store123p"
    key-alias: "easygoKey"
  port: 8443

management:
  health:
    defaults:
      enabled: false
    db:
      enabled: true
    ping:
      enabled: true
  info:
    defaults:
      enabled: false
    git:
      enabled: true
      mode: simple
    env:
      enabled: true
    build:
      enabled: true
  endpoints:
    web:
      discovery:
        enabled: true
      exposure:
        include: beans,env,health,info
    enabled-by-default: false
  endpoint:
    beans:
      enabled: true
    env:
      enabled: true
      show-values: always
    health:
      show-details: always
      show-components: always
      enabled: true
    info:
      enabled: true

logging.level:
    org.springframework.security.web.csrf.CsrfFilter: debug

