
spring:
  jpa:
    # see: https://stackoverflow.com/questions/30549489/what-is-this-spring-jpa-open-in-view-true-property-in-spring-boot
    open-in-view: false
  thymeleaf:
    prefix: "classpath:/view-resources/"
    view-names: "*.th"
    suffix: ".html"

server:
  servlet:
    context-path: "/easygo-web"
  ssl:
    enabled: true
    key-store: "classpath:easygoKs"
    key-store-type: "PKCS12"
    key-store-password: "store123p"
    key-alias: "easygoKey"
  port: 8080

management:
  endpoint:
    health:
      show-details: always
      show-components: always
