= Easygo accounting application

Web-based, open-source application for *financial accounting*. Implements the axioms of double-entry (Venetian method) accounting.

== Technology stack

The Easygo is built on top of several mainstream database, backend and web-frontend technologies including:

* Oracle XE Database
* Spring/Spring Boot Framework
* Angular

== Project Structure

Split into several modules:

=== angular-ui

Client (front-end) single-page application written in Angular framework.

=== db-exec

Contains

* the DB setup and migration scripts
* data fixture files and tools for loading them (for dev and testing purposes)

=== domain-financial-accounting

The domain-layer application code.

=== web-application

Web @Controller(s), endpoint mappings, a @SpringBootApplication and other supporting code necessary
for running backend web service. Embeds of *domain-financial-accounting* and *angular-ui* modules.

== Installation and Running

=== Prerequisites

You need the following software installed on your machine:

* JDK 17+

* NodeJS v18+

* Docker (on Windows the best choice is probably Docker Desktop)

=== JDK and NodeJS

Make sure you have properly set the `JAVA_HOME` environment variable, and the `%JAVA_HOME%\bin` (on Windows) or
`${JAVA_HOME}/bin` (on Linux) is added to the `PATH`. Proper installation can be verified by running:

[source,bash]
----
$ echo ${JAVA_HOME}
/opt/jdk-17.0.4+8
$
$ java --version
openjdk 17.0.4 2022-07-19
OpenJDK Runtime Environment Temurin-17.0.4+8 (build 17.0.4+8)
OpenJDK 64-Bit Server VM Temurin-17.0.4+8 (build 17.0.4+8, mixed mode, sharing)
$
$ javac --version
javac 17.0.4
$
$
$ node --version
v18.15.0
$ npm --version
9.5.0
$
----

=== Start Oracle XE Database server

Inside `docker-infra/compose.yaml`, you can find the `run-oracle-server` service definition for running Oracle XE Database server. First, create the container:

[source,bash]
----
$ cd ./docker-infra
$ docker compose create run-oracle-server
----

an then start it:
[source,bash]
----
$ docker compose start run-oracle-server
----
First start of this container may take ~45 seconds as the database files are being initialized. Next starts should be quicker.

[#installation_create_initial_schema]
=== Create initial schema

From source root:

[source,bash]
----
$ ./gradlew :db-exec:createEasygoSysSchema
----

=== Migrate
Database schema migrations are powered by https://flywaydb.org/documentation/[Flyway]. They can be executed with dedicated Gradle task:

[source,bash]
----
$ ./gradlew :db-exec:oracleBaselineAndMigrate
----

=== Load data fixtures

[source,bash]
----
$ ./gradlew :db-exec:loadFixtures
----

=== Execute complete build
This includes `npm install` and `ng build` of the Angular UI.

----
$ ./gradlew build
----

=== Run the application locally

[source,bash]
----
$ ./gradlew -PskipAngularBuild=true -PskipNpmInstall=true :web-application:bootRun
----
If everything is setup correctly you should be able to access working application
under https://localhost:8443/easygo-web/ .
You should be able to log in with +
Username: *john@example.com* +
Password: *john* 

== Installation troubleshooting

=== In case of broken database schema (SQL related errors in console)

You can try dropping the schemas and recreating from scratch. There are two Gradle tasks to remove *all*
schemas created previously. Stop application if it's running (Oracle may refuse to drop
the schema if there is an active connection) and execute:

[source,bash]
----
$ ./gradlew :db-exec:dropTenantSchemas :db-exec:dropEasygoSysSchema
----

// In order to create so called Cross References in AsciiDoc do:
//   https://docs.asciidoctor.org/asciidoc/latest/blocks/assign-id/
//   https://docs.asciidoctor.org/asciidoc/latest/macros/xref/#internal-cross-references
//   https://stackoverflow.com/questions/58512730/links-to-sections-of-same-page-in-asciidoc
// Similar thing could be achieved with:
//   link:#installation_create_initial_schema[Create initial schema]
//
Then, repeat steps from <<installation_create_initial_schema>>.

