services:
  run-oracle-server:
    container_name: "easygo.oracle-server"
    image: "gvenzl/oracle-xe:21.3.0"
    environment:
      ORACLE_PASSWORD: "oraclepx0"
    networks:
      - "easygo-bridge-net"
    ports:
      - "0.0.0.0:1521:1521/tcp"
    volumes:
      - type: "volume"
        source: "oracle-data"
        target: "/opt/oracle/oradata"
        read_only: false
    deploy:
      resources:
        limits:
          memory: 2G
  run-tomcat-web:
    image: "easygo/tomcat-web"
    build:
      context: "../"
      dockerfile: "./docker-infra/services/run-tomcat-web/Dockerfile"
    container_name: "easygo.tomcat-web"
    networks:
      - "easygo-bridge-net"
    ports:
      - "0.0.0.0:80:8080/tcp"
    env_file:
      - "../config/app-db.properties"
networks:
  easygo-bridge-net:
    driver: "bridge"
    name: "easygo-net"
volumes:
  oracle-data:
    name: "easygo.oracle-data-volume"
